FROM node:16

ARG S3_BUCKET_NAME
ARG DATABASE_URL
ARG S3_REGION
ARG S3_ACCESS_KEY_ID
ARG S3_SECRET_ACCESS_KEY
ARG POSTGRES_USERNAME
ARG POSTGRES_PASSWORD

ENV S3_BUCKET_NAME=$S3_BUCKET_NAME
ENV DATABASE_URL=$DATABASE_URL
ENV S3_REGION=$S3_REGION
ENV S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
ENV S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
ENV POSTGRES_USERNAME=$POSTGRES_USERNAME
ENV POSTGRES_USERNAME=$POSTGRES_USERNAME

WORKDIR /usr/src/app

COPY . .

RUN yarn install

COPY . .

RUN yarn build

EXPOSE 3000

CMD [ "yarn", "start" ]