version: '3'

services:
  keystone:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keystone.rule=Host(`admin.gcode-gizmos.${PRIMARY_DOMAIN}`)"
      - "traefik.http.routers.keystone.entrypoints=websecure"
      - "traefik.http.routers.keystone.tls.certresolver=le"
    networks:
      - root_traefik-public
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - root_traefik-public
volumes:
  db-data:
networks:
  root_traefik-public:
    external: true
