version: '3'

services:
  keystone:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gcode-gizmos-frontend.rule=Host(`admin.gcode-gizmos.${PRIMARY_DOMAIN}`)"
      - "traefik.http.routers.gcode-gizmos-frontend.entrypoints=websecure"
      - "traefik.http.routers.gcode-gizmos-frontend.tls.certresolver=le"
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
